# Generated by Django 6.0.5 on 2026-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Contract', 'Contract')], default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Engineering', 'Engineering'), ('Customer Service', 'Customer Service')], max_length=50),
        ),
    ]
