# Generated by Django 6.0.5 on 2026-05-10 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_type_alter_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], default='Tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(help_text='e.g. $100k - $120k', max_length=100),
        ),
    ]
